version: '3.8'

services:

  scout-asana-mcp:
    build:
      context: ./scout-asana-mcp
      dockerfile: Dockerfile
    container_name: scout-asana-mcp
    environment:
      - ASANA_ACCESS_TOKEN=${ASANA_ACCESS_TOKEN}
    ports:
      - "8001:8001"
    restart: unless-stopped
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

  scout-npid-mcp:
    build:
      context: ../npid-mcp-server
      dockerfile: Dockerfile
    container_name: scout-npid-mcp
    environment:
      - NPID_USERNAME=${NPID_USERNAME}
      - NPID_PASSWORD=${NPID_PASSWORD}
      - NPID_BASE_URL=${NPID_BASE_URL:-https://dashboard.nationalpid.com}
      - NPID_REFRESH_INTERVAL_MINUTES=${NPID_REFRESH_INTERVAL_MINUTES:-90}
      - NPID_KEEPALIVE_INTERVAL_MINUTES=${NPID_KEEPALIVE_INTERVAL_MINUTES:-20}
      - NPID_TOKEN_PATH=/app/state/npid_tokens.json
    volumes:
      - ../state:/app/state
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  asana-mcp-auth:
